---
- name: Slack Notification
  hosts: all
  connection: local
  gather_facts: false
  tasks:

  vars:
    slack_message: >-
      The change has been closed with "{{ cr_close_status |default('successful')}}" result.
      Please go to <http://{{ public_ip_address }}>

  roles:
    - demo.process.slack
  run_once: yes